language: python
python:
- "2.7"
before_install:
- openssl aes-256-cbc -K $encrypted_e6b2e2d8422a_key -iv $encrypted_e6b2e2d8422a_iv -in ota-rocks-sa.json.enc -out ota-rocks-sa.json -d
install:
- pip install -U pip
- pip install -r requirements.txt -t lib/
- pip install -r requirements.txt
script:
- python test_initial.py
deploy:
  provider: gae
  keyfile: "ota-rocks-sa.json"
  project: "ota-rocks"
  on: master

